// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/vehicle.go

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	entity "github.com/lucas-moura1/gobrax-challenge/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockVehicleUsecase is a mock of VehicleUsecase interface.
type MockVehicleUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleUsecaseMockRecorder
}

// MockVehicleUsecaseMockRecorder is the mock recorder for MockVehicleUsecase.
type MockVehicleUsecaseMockRecorder struct {
	mock *MockVehicleUsecase
}

// NewMockVehicleUsecase creates a new mock instance.
func NewMockVehicleUsecase(ctrl *gomock.Controller) *MockVehicleUsecase {
	mock := &MockVehicleUsecase{ctrl: ctrl}
	mock.recorder = &MockVehicleUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleUsecase) EXPECT() *MockVehicleUsecaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockVehicleUsecase) Delete(vehicleId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", vehicleId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVehicleUsecaseMockRecorder) Delete(vehicleId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVehicleUsecase)(nil).Delete), vehicleId)
}

// GetAll mocks base method.
func (m *MockVehicleUsecase) GetAll() ([]*entity.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*entity.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockVehicleUsecaseMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockVehicleUsecase)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockVehicleUsecase) GetById(vehicleId int) (*entity.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", vehicleId)
	ret0, _ := ret[0].(*entity.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockVehicleUsecaseMockRecorder) GetById(vehicleId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockVehicleUsecase)(nil).GetById), vehicleId)
}

// Update mocks base method.
func (m *MockVehicleUsecase) Update(vehicleId int, updateVehicle *entity.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", vehicleId, updateVehicle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVehicleUsecaseMockRecorder) Update(vehicleId, updateVehicle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVehicleUsecase)(nil).Update), vehicleId, updateVehicle)
}
